spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true	# Enables gateway to create routes based on services registered with service discovery
        lowerCaseServiceId: true

server:
  port: 8072
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
